zend/application/Bootstrap.php     Set default pagination control.
zend/application/models/Tag.php
    Add static methods:
        ids()       Given an array of tag names, return an array of matching
                    tag identifiers
        select()    Generate a Zend_Db_Select instance to retrieve a set of
                    tags

    Modify fetch() to use select().

zend/application/models/UserItem.php
    Change the constructor to pull foreign table initialization data from id.

    Add static methods:
        select()        Generate a Zend_Db_Select instance to retrieve a set of
                        userItems
        getItemSelect() Given a Zend_Db_Select instance from self::select() OR
                        a set of arrays of tag, user, and item restrictions,
                        generate a new Zend_Db_Select instance capable of
                        retrieving the unique items from the set of all matched
                        userItems
        itemIds()       Use getItemSelect() to retrieve the set of unique item
                        identifiers
        paginator()     A forey into creating a paginator using self::select()
                        This will probably go away.

    Modify fetch() to use select().
    
zend/application/controllers/IndexController.php
    Generate a paginator to present the matching userItems.

    Pass the userItem selector to the view script to allow it to generate the
    matching tag cloud.  This needs to be pretty late since it won't be
    presented in all views (e.g. JSON).


zend/application/views/scripts/index/index.phtml
    Use the paginator to present items.

    Add code to generate a presentation of the tag cloud if we were passed a
    userItem select instance.

zend/application/views/scripts/paginationControl.phtml
    Add a pagination control view partial to generate a site-consistent
    pagination control.

zend/library/Connexions/Model.php
    Use '(unset) var;' instead of 'unset(var);' to avoid a funkey fatal error
        Fatal error: Cannot unset string offsets

zend/application/layouts/layout.phtml
    Pull the right column content from layout()->right.

zend/tests/library/model_userItem.php
    Test for Model_UserItem::select